### ISSUE TITLE
Patrón adapter para fitness (update + end?)

### ISSUE THREAD

**Issue by J-888** [hecoding/Pac-Man#1]

**Comment by J-888** [comment]
¿Descartamos este issue?

EDIT: fallo mío, te entendí otra cosa (que ya no tendría sentido) cuando pensamos en usar el patron

**Comment by hecoding** [comment]
@J-888 para nada, lo haremos cuando se pueda. a no ser que ya esté implementado en jeco (lo dudo)

**Comment by hecoding** [comment]
fixed [here](https://github.com/hecoding/Pac-Man/commit/0db8a1a7a598d39d71632611df2c8746abd397e5) (forgot to mention when commiting)
