### ISSUE TITLE
Change mutation operator

### ISSUE THREAD

**Issue by hecoding** [hecoding/Pac-Man#27]
Ahora sólo aplica la mutación a los individuos que salen de los cruces, cambiarla a que potencialmente todos los individuos de la población puedan ser afectados.

**Comment by Jorjatorz** [comment]
Esto ya es así, no hace falta ningún cambio.
Cierra el issue una ves hayas visto que es así.

**Comment by hecoding** [comment]
Es verdad, el operador de cruce devuelve los padres si no se cruza nada.
