### ISSUE TITLE
dudas CustomExecutor

### ISSUE THREAD

**Issue by hecoding** [hecoding/Pac-Man#4]
- No entiendo por qué hay un parámetro fitness que al final se iguala a algo, cuando simplemente se puede quitar el `void` y hacer que devuelva es mismo fitness.

- No entiendo que en el bucle se decremente el fitness para que al salir de él SE PISE CON EL MAXSCORE

- No entiendo por qué se quiere coger la maxima puntuación en el bucle si el juego sólo se está ejecutando una vez

Hasta que no resolvamos todo esto no podemos hacer #1

**Comment by J-888** [comment]
> No entiendo que en el bucle se decremente el fitness para que al salir de él SE PISE CON EL MAXSCORE

Es código residual de cuando lo calculabamos con el tiempo. Hay que cambiarlo cuando hagamos patrón fitness

**Comment by hecoding** [comment]
Resolución:
- meh, lo que sea
- borrar fitness.decrement() (deprecated)
- está mal, hay que eliminar el if y llamar a maxscore al final

Asegurarse de que el getScore no se reinicia al cambiar de nivel
Para @Jorjatorz de nosotros :heart:
