### ISSUE TITLE
GrammaticalAdapterController cleanup 2

### ISSUE THREAD

**Issue by J-888** [hecoding/Pac-Man#5]
- Cambiar el nombre de la variable ghost a algo mas representativo. Si es mas cercano, "closestGhost". Evitar confusiones.
- Obtener solo fantasmas y pildoras cercanas cuando sea necesario, según casos del switch e ifs.

**Comment by hecoding** [comment]
my bad
me gusta que critiques el código, cuando más limpio mejor
